// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
await Firebase.initializeApp(
options: DefaultFirebaseOptions.currentPlatform,
);

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOuqXY3VTQhzY39-IvMmicTHqSReYw-18',
    appId: '1:655088261531:web:2626f854761fb792baa93e',
    messagingSenderId: '655088261531',
    projectId: 'project-rpl3bpnp',
    authDomain: 'project-rpl3bpnp.firebaseapp.com',
    storageBucket: 'project-rpl3bpnp.appspot.com',
    measurementId: 'G-FW4ZX1P7N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDInw14N4WDKpi368rz5KXL6LYwCP96mMQ',
    appId: '1:655088261531:android:73614f972e783e49baa93e',
    messagingSenderId: '655088261531',
    projectId: 'project-rpl3bpnp',
    storageBucket: 'project-rpl3bpnp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClsDSeqrbP9_HGAexkYWVDEGkkeBwYJ_k',
    appId: '1:655088261531:ios:0b3d1893fe15e638baa93e',
    messagingSenderId: '655088261531',
    projectId: 'project-rpl3bpnp',
    storageBucket: 'project-rpl3bpnp.appspot.com',
    iosBundleId: 'com.udacoding.mapsFlutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClsDSeqrbP9_HGAexkYWVDEGkkeBwYJ_k',
    appId: '1:655088261531:ios:0b3d1893fe15e638baa93e',
    messagingSenderId: '655088261531',
    projectId: 'project-rpl3bpnp',
    storageBucket: 'project-rpl3bpnp.appspot.com',
    iosBundleId: 'com.udacoding.mapsFlutter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOuqXY3VTQhzY39-IvMmicTHqSReYw-18',
    appId: '1:655088261531:web:7c6ea52f6829efd4baa93e',
    messagingSenderId: '655088261531',
    projectId: 'project-rpl3bpnp',
    authDomain: 'project-rpl3bpnp.firebaseapp.com',
    storageBucket: 'project-rpl3bpnp.appspot.com',
    measurementId: 'G-0P0JQ7MXSW',
  );
}
